"""Compute summary statistics for the current run.

Inputs:
- data/simulated/gw_triggers.csv
- data/simulated/grb_triggers.csv
- data/results/coincident_events.csv

Outputs:
- data/results/summary_stats.txt
"""

from pathlib import Path
import logging

import numpy as np
import pandas as pd

import config


def ranking_statistic(p_signal, p_noise):
    """Simple ranking statistic (placeholder)."""
    return p_signal / p_noise


def compute_summary_stats(gw, grb, coincidences):
    """Compute summary metrics for the simulated run."""
    stats = {
        "total_gw": len(gw),
        "total_grb": len(grb),
        "coincidence_count": len(coincidences)
    }

    if len(coincidences) > 0 and "angle_rad" in coincidences.columns:
        angles = coincidences["angle_rad"].to_numpy()
        stats["min_angular_sep_rad"] = float(np.min(angles))
        stats["mean_angular_sep_rad"] = float(np.mean(angles))
        stats["max_angular_sep_rad"] = float(np.max(angles))
    else:
        stats["min_angular_sep_rad"] = None
        stats["mean_angular_sep_rad"] = None
        stats["max_angular_sep_rad"] = None

    if len(coincidences) > 0 and "rank_lambda" in coincidences.columns:
        lambdas = coincidences["rank_lambda"].replace([np.inf, -np.inf], np.nan).dropna()
        if len(lambdas) > 0:
            stats["mean_rank_lambda"] = float(np.mean(lambdas))
            stats["max_rank_lambda"] = float(np.max(lambdas))
        else:
            stats["mean_rank_lambda"] = None
            stats["max_rank_lambda"] = None

        if "p_H1_D" in coincidences.columns:
            p_h1 = coincidences["p_H1_D"].replace([np.inf, -np.inf], np.nan).dropna()
            if len(p_h1) > 0:
                stats["mean_p_H1"] = float(np.mean(p_h1))
                stats["max_p_H1"] = float(np.max(p_h1))
            else:
                stats["mean_p_H1"] = None
                stats["max_p_H1"] = None
    else:
        stats["mean_rank_lambda"] = None
        stats["max_rank_lambda"] = None
        stats["mean_p_H1"] = None
        stats["max_p_H1"] = None

    stats["DELTA_T_seconds"] = config.DELTA_T
    stats["DELTA_OMEGA_rad"] = config.DELTA_OMEGA
    stats["PRIOR_HNN"] = config.PRIOR_HNN
    stats["PRIOR_HSN"] = config.PRIOR_HSN
    stats["PRIOR_HNS"] = config.PRIOR_HNS
    stats["PRIOR_HSS"] = config.PRIOR_HSS
    stats["PRIOR_HC"] = config.PRIOR_HC
    return stats


def write_summary(path, stats):
    """Write the summary stats text report."""
    def fmt(value):
        if value is None:
            return ""
        return f"{value}"

    lines = [
        "Summary statistics",
        "Generated by: src/statistics.py",
        "",
        "# Field descriptions",
        "# total_gw: number of simulated GW triggers",
        "# total_grb: number of simulated GRB triggers",
        "# coincidence_count: number of GW-GRB pairs passing time+sky thresholds",
        "# min_angular_sep_rad: minimum angular separation among coincidences (radians)",
        "# mean_angular_sep_rad: mean angular separation among coincidences (radians)",
        "# max_angular_sep_rad: maximum angular separation among coincidences (radians)",
        "# mean_rank_lambda: mean Bayesian ranking statistic Lambda",
        "# max_rank_lambda: maximum Lambda",
        "# mean_p_H1: mean posterior signal probability p(H1|D)",
        "# max_p_H1: maximum posterior signal probability p(H1|D)",
        "# DELTA_T_seconds: time coincidence threshold (seconds)",
        "# DELTA_OMEGA_rad: sky coincidence threshold (radians)",
        "# PRIOR_HNN/HSN/HNS/HSS/HC: hypothesis priors used in ranking",
        "",
        f"total_gw = {fmt(stats.get('total_gw'))}",
        f"total_grb = {fmt(stats.get('total_grb'))}",
        f"coincidence_count = {fmt(stats.get('coincidence_count'))}",
        f"min_angular_sep_rad = {fmt(stats.get('min_angular_sep_rad'))}",
        f"mean_angular_sep_rad = {fmt(stats.get('mean_angular_sep_rad'))}",
        f"max_angular_sep_rad = {fmt(stats.get('max_angular_sep_rad'))}",
        "",
        f"mean_rank_lambda = {fmt(stats.get('mean_rank_lambda'))}",
        f"max_rank_lambda = {fmt(stats.get('max_rank_lambda'))}",
        f"mean_p_H1 = {fmt(stats.get('mean_p_H1'))}",
        f"max_p_H1 = {fmt(stats.get('max_p_H1'))}",
        "",
        "# Coincidence thresholds",
        f"DELTA_T_seconds = {fmt(stats.get('DELTA_T_seconds'))}",
        f"DELTA_OMEGA_rad = {fmt(stats.get('DELTA_OMEGA_rad'))}",
        "",
        "# Hypothesis priors",
        f"PRIOR_HNN = {fmt(stats.get('PRIOR_HNN'))}",
        f"PRIOR_HSN = {fmt(stats.get('PRIOR_HSN'))}",
        f"PRIOR_HNS = {fmt(stats.get('PRIOR_HNS'))}",
        f"PRIOR_HSS = {fmt(stats.get('PRIOR_HSS'))}",
        f"PRIOR_HC = {fmt(stats.get('PRIOR_HC'))}",
        ""
    ]

    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    gw_path = Path("data/simulated/gw_triggers.csv")
    grb_path = Path("data/simulated/grb_triggers.csv")
    coinc_path = Path("data/results/coincident_events.csv")
    out_path = Path("data/results/summary_stats.txt")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    gw = pd.read_csv(gw_path) if gw_path.exists() else pd.DataFrame()
    grb = pd.read_csv(grb_path) if grb_path.exists() else pd.DataFrame()

    if coinc_path.exists():
        coincidences = pd.read_csv(coinc_path)
    else:
        coincidences = pd.DataFrame(
            columns=[
                "gw_event_id",
                "grb_event_id",
                "gw_time",
                "grb_time",
                "delta_t",
                "angle_rad",
                "rank_lambda",
                "p_H0_D",
                "p_H1_D"
            ]
        )

    stats = compute_summary_stats(gw, grb, coincidences)
    write_summary(out_path, stats)
    logging.info("Saved summary stats to %s", out_path)


if __name__ == "__main__":
    main()
