from pathlib import Path

import numpy as np
import pandas as pd

import config


def ranking_statistic(p_signal, p_noise):
    return p_signal / p_noise


def compute_summary_stats(gw, grb, coincidences):
    stats = {
        "total_gw": len(gw),
        "total_grb": len(grb),
        "coincidence_count": len(coincidences)
    }

    if len(coincidences) > 0 and "angle_rad" in coincidences.columns:
        angles = coincidences["angle_rad"].to_numpy()
        stats["min_angular_sep_rad"] = float(np.min(angles))
        stats["mean_angular_sep_rad"] = float(np.mean(angles))
        stats["max_angular_sep_rad"] = float(np.max(angles))
    else:
        stats["min_angular_sep_rad"] = None
        stats["mean_angular_sep_rad"] = None
        stats["max_angular_sep_rad"] = None

    stats["DELTA_T_seconds"] = config.DELTA_T
    stats["DELTA_OMEGA_rad"] = config.DELTA_OMEGA
    return stats


def write_summary(path, stats):
    def fmt(value):
        if value is None:
            return ""
        return f"{value}"

    lines = [
        "Summary statistics",
        "Generated by: src/statistics.py",
        "",
        f"total_gw = {fmt(stats.get('total_gw'))}",
        f"total_grb = {fmt(stats.get('total_grb'))}",
        f"coincidence_count = {fmt(stats.get('coincidence_count'))}",
        f"min_angular_sep_rad = {fmt(stats.get('min_angular_sep_rad'))}",
        f"mean_angular_sep_rad = {fmt(stats.get('mean_angular_sep_rad'))}",
        f"max_angular_sep_rad = {fmt(stats.get('max_angular_sep_rad'))}",
        "",
        "# Coincidence thresholds",
        f"DELTA_T_seconds = {fmt(stats.get('DELTA_T_seconds'))}",
        f"DELTA_OMEGA_rad = {fmt(stats.get('DELTA_OMEGA_rad'))}",
        ""
    ]

    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    gw_path = Path("data/simulated/gw_triggers.csv")
    grb_path = Path("data/simulated/grb_triggers.csv")
    coinc_path = Path("data/results/coincident_events.csv")
    out_path = Path("data/results/summary_stats.txt")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    gw = pd.read_csv(gw_path) if gw_path.exists() else pd.DataFrame()
    grb = pd.read_csv(grb_path) if grb_path.exists() else pd.DataFrame()

    if coinc_path.exists():
        coincidences = pd.read_csv(coinc_path)
    else:
        coincidences = pd.DataFrame(columns=["gw_event_id", "grb_event_id", "gw_time", "grb_time", "angle_rad"])

    stats = compute_summary_stats(gw, grb, coincidences)
    write_summary(out_path, stats)
    print(f"Saved summary stats to {out_path}")


if __name__ == "__main__":
    main()
